import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { APP_NAME } from "@/utils/constants";

const font = Prompt({
  weight: ["100", "300", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main
          className="min-h-screen min-w-full bg-gradient-to-r from-blue-200 to-cyan-200 p-4"
          data-theme="light"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
