import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { APP_NAME } from "@/utils/constants";
import Navbar from "@/components/organisms/Navbar";
import Footer from "@/components/organisms/Footer";
import Modal from "@/components/molecules/Modal";

const font = Prompt({
  weight: ["100", "300", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        <Modal />
        <main
          className="body-bg min-h-screen min-w-full p-4"
          data-theme="light"
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
